### ISSUE TITLE
Dúvidas sobre avisos na compilação

### ISSUE THREAD

**Issue by vpereira13** [courselab/imf2021-cerv#1]
Apesar de ser gerado executável `decode` e conseguirmos utilizar como foi proposto pelo exercício, ficamos em dúvida referente às saídas geradas pela linha de comando na última etapa.

Segue a saída gerada pelo terminal.
```
gcc -m32 fix.o decode.o -L. -Wl,-rpath='$ORIGIN' -lcrak -lcypher -o decode
/usr/bin/ld: decode.o: aviso: relocalização em secção só de leitura ".rodata"
/usr/bin/ld: aviso: a criar DT_TEXTREL num PIE
```
Agradeço se conseguir explicar.

**Comment by monacofj** [comment]
Estranho, testei aqui e não reporta nenhum erro.
Quais as saídas que você obtem com

```
gcc --version
```

**Comment by vpereira13** [comment]
> Estranho, testei aqui e não reporta nenhum erro.
> Quais as saídas que você obtem com
> 
> ```
> gcc --version
> ```
> 
> E qual a plataforma de build?

```
ζ gcc --version
gcc (GCC) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ζ uname -r
5.13.8-arch1-1
```

**Comment by monacofj** [comment]
Tente compilar o binário com -fno-pic -fno-pie como teste.

**Comment by vpereira13** [comment]
> -fno-pic -fno-pie

A adição do `-no-pie` na regra de compilação deu certo, fez com que não gerasse mais as mensagens de aviso.

Procurei na documentação do `gcc` sobre o que era a flag e estava dizendo:
```
-no-pie
           Don't produce a dynamically linked position independent executable.
```

Obrigado, professor. Acha que precisa ser feita a atualização no código?

**Comment by monacofj** [comment]
Sobre atualizar, só se você quiser deixar 100%, mas aqui pra mim nem aparece o erro.
